### ISSUE TITLE
Salaires : ajouter un type de règle

### ISSUE THREAD

**Issue by katia-d4e** [d4e-digital-4-efficiency/d4e-salaires-v14-katia#1]
Bonjour Youssef

Dans les règles des salaires, il faut ajouter une liste déroulante Type de règle.
Cette liste doit contenir les éléments suivants :

- Rubrique
- Base de calcul
- Donnée de stockage

![image](https://user-images.githubusercontent.com/83944195/122743823-aa07fc00-d287-11eb-9847-a0faadc12321.png)

Ce champ doit être obligatoire.

Attention, avant de faire ce développement, il faut que tous les autres développements sur les règles soient repris en v14 et installé sur cette base. (voir avec Farès)

Merci
Katia

**Comment by katia-d4e** [comment]
Bonjour Youssef,

C'est ok pour ce point, il peut démarrer. La migration des développements en v14 a été faite.

merci
Katia

**Comment by youssef-hamrouni** [comment]
Bonjour ,

C'est fait sur la branch : 0107_salaire
module : l10n_ch_hr_payroll
commit : f95dd46

Merci !

**Comment by katia-d4e** [comment]
Bonjour,

Pouvez-vous mettre en staging svp ?

Merci
Katia

**Comment by youssef-hamrouni** [comment]
Bonjour 

c'est fait en main + staging 

Merci et excellent journée !

**Comment by katia-d4e** [comment]
C'est parfait comme ça.
merci

**Comment by katia-d4e** [comment]
bonjour,

Peux-tu ajouter un nouveau type de règle
- Rubriques - Part employeur

Merci
Katia

**Comment by youssef-hamrouni** [comment]
Bonjour , 

C'est fait en staging ! 
module :l10n_ch_hr_payroll
commit:6ca9572
branch:0107_salaire
