### ISSUE TITLE
Salaires: ajouter montants dans les contrats

### ISSUE THREAD

**Issue by katia-d4e** [d4e-digital-4-efficiency/d4e-salaires-v14-katia#10]
Bonjour,

Dans les contrats des employés, il faudrait ajouter les champs suivants dans les montants (ordre selon capture ci-dessous) :

- Frais forfaitaire de voiture
- Frais forfaitaire pour expatriés
- Autre frais forfaitaires

Il faudrait renommer les champs suivants :
- Allocation pour enfant => Allocations familiale
- LPP Fixe => Cotisation LPP fixe
- LPP fixe PP => Cotisation LPP fixe - Part employeur

A voir également si on peut mettre les montants en 2 colonnes, comme ceci :

![image](https://user-images.githubusercontent.com/83944195/128319419-e969c852-9553-43a8-9f87-66415343c118.png)

Merci
Katia

**Comment by youssef-hamrouni** [comment]
Bonjour , 

C'est fait sur la branch : 0107_salaire
module : l10n_ch_hr_payroll
commit : e15e46b

Merci !

**Comment by katia-d4e** [comment]
Merci, tu peux mettre en staging ?
Merci
Katia
